version: '2'

services:
  app:
    image: 'gratis-brocki:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gratisbrocki
    ports:
      - 8080:8080
          
  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=gratisbrocki
    ports:
      - 5432:5432
